"""
Writes the runtime's view of the uploaded exterior from assets/train/asset_ids.json:

  python tools/trainshell/gen_config.py

  src/shared/Config/TrainShell.luau     mesh ids, centres and sizes in train space, livery roles
  src/server/TrainLooks.model.json      SurfaceAppearance templates (Rojo -> ServerScriptService.Server.TrainLooks)

Car pieces are named <Car>_<Piece>; kit pieces (DoorLeafL/R, Bogie, Wheel) carry an `anchor`:
where the primitive they stand in for has its centre, in the kit's own frame.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ids = json.load(open(os.path.join(ROOT, "assets", "train", "asset_ids.json")))

CARS = {
    "GuardsVan": (-90, -66),
    "LastTrainOut": (-63, -44.5),
    "CrewSaloon": (-41.5, -23),
    "Workshop": (-20, -1.5),
    "Stores": (1.5, 20),
    # the engine and her tender (engine2.py): the primitive centres each one owns
    "Tender": (21.5, 50.5),
    "Locomotive": (50.5, 100),
}
PIECES = {
    # piece: livery role, look, casts a shadow
    "Shell": ("Body", "{car}", True),
    "Trim": ("Trim", "{car}", False),
    "Roof": ("Roof", "{car}", True),
    "Lens": ("Lamp", None, False),
    "Sign": (None, "{car}_Sign", False),
    # round 2
    "Fittings": (None, "{car}", True),
    "Glow": ("Lamp", None, False),
    "Haze": ("Lamp", None, False),
    # each side has its own 1024 atlas (a SurfaceAppearance map is capped at 1024)
    "ShellP": ("Body", "{car}_P", True),
    "ShellN": ("Body", "{car}_N", True),
    "TrimP": ("Trim", "{car}_P", False),
    "TrimN": ("Trim", "{car}_N", False),
    "FittingsP": (None, "{car}_P", True),
    "FittingsN": (None, "{car}_N", True),
    # round 3: roof and end loads (Workshop, Stores), split by side like the shell
    "Crate": (None, "{car}", True),
    "CrateP": (None, "{car}_P", True),
    "CrateN": (None, "{car}_N", True),
    "Tarp": (None, "{car}", True),
    "TarpP": (None, "{car}_P", True),
    "TarpN": (None, "{car}_N", True),
    # the Guard's Van's red tail lenses: unbaked, like the Lens
    "Tail": ("Lamp", None, False),
    # car-specific heavy door leaves (Workshop, Stores), painted in the platform side's atlas;
    # a car that has them uses these instead of the kit's leaves
    "DoorLeafL": ("Accent", "{car}_P", True),
    "DoorLeafR": ("Accent", "{car}_P", True),
    # the engine's boiler, smokebox, stack and cylinder lagging (its own atlas, <car>_B)
    "Boiler": (None, "{car}_B", True),
}
# per piece: the door lamps' light lives on the Lens; the window veil is mostly see-through
EXTRA = {"Lens": {"light": "true"}, "Haze": {"transparency": "0.86"}, "Tail": {"color": "{ 0.78, 0.07, 0.04 }"}}
KIT = {
    "DoorLeafL": ((0, 0, 0), "Accent"),
    "DoorLeafR": ((0, 0, 0), "Accent"),
    "Bogie": ((0, -3, 0), None),
    "Wheel": ((0, 0, 0), None),
    # round 3: the engine's driving wheels (red centres), coupling rods, and a coal heap per CoalTier ball
    "DriveWheelP": ((0, 0, 0), None),
    "DriveWheelN": ((0, 0, 0), None),
    "RodP": ((0, 0, 0), None),
    "RodN": ((0, 0, 0), None),
    "CoalLump": ((0, 0, 0), None),
}
KIT_EXTRA = {"DriveWheelP": {"color": "{ 0.518, 0.133, 0.11 }"}, "DriveWheelN": {"color": "{ 0.518, 0.133, 0.11 }"}}


def num(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def vec(v):
    return "{ " + ", ".join(num(x) for x in v) + " }"


lines = [
    "--!strict",
    "--[[",
    "\tThe train's Blender exterior, as uploaded (generated by tools/trainshell/gen_config.py from",
    "\tassets/train/asset_ids.json; do not edit by hand). Centres and sizes are train space (studs).",
    "\tBuilders/TrainShell puts these on the primitive train; set Enabled = false for the old look.",
    "]]",
    "",
    "export type Piece = {",
    "\tmesh: number,",
    "\tcenter: { number },",
    "\tsize: { number },",
    "\tlivery: string?,",
    "\tlook: string?,",
    "\tshadow: boolean,",
    "\tlight: boolean?,",
    "\ttransparency: number?,",
    "\tcolor: { number }?,",
    "}",
    "",
    "export type KitPiece = {",
    "\tmesh: number,",
    "\tcenter: { number },",
    "\tsize: { number },",
    "\tanchor: { number },",
    "\tlook: string?,",
    "\tlivery: string?,",
    "\tcolor: { number }?,",
    "}",
    "",
    "export type Car = {",
    "\tx0: number,",
    "\tx1: number,",
    "\tpieces: { [string]: Piece },",
    "\tlights: { { number } }?,",
    "\thideWalls: boolean?,",
    "\tengine: boolean?,",
    "\tretire: { { number } }?,",
    "}",
    "",
    "local TrainShell: {",
    "\tEnabled: boolean,",
    "\tKitLook: string,",
    "\tLampLight: { Range: number, Brightness: number },",
    "\tCars: { [string]: Car },",
    "\tKit: { [string]: KitPiece },",
    "} = {",
    "\tEnabled = true,",
    '\tKitLook = "Kit",',
    "\t-- a steady glow under each door lamp, so the doors read from the platform at night",
    "\tLampLight = { Range = 9, Brightness = 0.7 },",
    "\tCars = {",
]
meshes = ids["meshes"]
for car, (x0, x1) in CARS.items():
    found = [p for p in PIECES if f"{car}_{p}" in meshes]
    if not found:
        continue
    lines.append(f"\t\t{car} = {{")
    lines.append(f"\t\t\tx0 = {num(x0)},")
    lines.append(f"\t\t\tx1 = {num(x1)},")
    meta_path = os.path.join(ROOT, "assets", "train", f"{car}.json")
    meta = json.load(open(meta_path)) if os.path.exists(meta_path) else {}
    spec = meta.get("spec", {})
    atlas = {p["name"]: p.get("atlas") for p in meta.get("parts", [])}
    if spec.get("lights") and any(k.startswith(f"{car}_Fittings") for k in meshes):
        # round 2: the lamps' lights sit at the lamps, and the side walls hide behind the carved skin
        lines.append("\t\t\tlights = { " + ", ".join(vec(v) for v in spec["lights"]) + " },")
        lines.append("\t\t\thideWalls = true,")
    if spec.get("retire") is not None:
        # the engine and tender retire exactly the primitives their meshes replace (engine2.retire_list)
        lines.append("\t\t\tengine = true,")
        lines.append("\t\t\tretire = {")
        for r in spec["retire"]:
            lines.append(f"\t\t\t\t{vec(r)},")
        lines.append("\t\t\t},")
    lines.append("\t\t\tpieces = {")
    for p in found:
        m = meshes[f"{car}_{p}"]
        livery, look, shadow = PIECES[p]
        fields = [f"mesh = {m['id']}", f"center = {vec(m['center'])}", f"size = {vec(m['size'])}"]
        if livery:
            fields.append(f'livery = "{livery}"')
        if look:
            # an engine part names its own atlas (the boiler's bands and domes bake into <car>_B)
            fields.append(f'look = "{atlas.get(f"{car}_{p}") or look.format(car=car)}"')
        fields.append(f"shadow = {'true' if shadow else 'false'}")
        for k, v in EXTRA.get(p, {}).items():
            fields.append(f"{k} = {v}")
        lines.append(f"\t\t\t\t{p} = {{ " + ", ".join(fields) + " },")
    lines.append("\t\t\t},")
    lines.append("\t\t},")
lines.append("\t},")
lines.append("\tKit = {")
for k, (anchor, livery) in KIT.items():
    if k not in meshes:
        continue  # not uploaded yet
    m = meshes[k]
    fields = [f"mesh = {m['id']}", f"center = {vec(m['center'])}", f"size = {vec(m['size'])}", f"anchor = {vec(anchor)}"]
    if livery:
        fields.append(f'livery = "{livery}"')
    if k.startswith("DoorLeaf") and "Doors_color" in ids["images"]:
        fields.append('look = "Doors"')  # round 2: the leaves have their own atlas
    for key, v in KIT_EXTRA.get(k, {}).items():
        fields.append(f"{key} = {v}")
    lines.append(f"\t\t{k} = {{ " + ", ".join(fields) + " },")
lines.append("\t},")
lines.append("}")
lines.append("")
lines.append("return TrainShell")
open(os.path.join(ROOT, "src", "shared", "Config", "TrainShell.luau"), "w", newline="\n").write("\n".join(lines) + "\n")

# SurfaceAppearance templates
images = ids["images"]
children = []


def look(name, prefix, pbr=True, normal=None):
    props = {"AlphaMode": "Overlay"}  # the part's (livery) colour shows under the colour map's alpha
    props["ColorMap"] = f"rbxassetid://{images[prefix + '_color' if pbr else prefix]}"
    if normal:
        props["NormalMap"] = f"rbxassetid://{images[normal]}"
    if pbr:
        props["NormalMap"] = f"rbxassetid://{images[prefix + '_normal']}"
        props["RoughnessMap"] = f"rbxassetid://{images[prefix + '_rough']}"
        props["MetalnessMap"] = f"rbxassetid://{images[prefix + '_metal']}"
    children.append({"name": name, "className": "SurfaceAppearance", "properties": props})


look("Kit", "Kit")
if "Doors_color" in images:
    look("Doors", "Doors")
for car in CARS:
    if f"{car}_color" in images:
        look(car, car)
    for tag in ("P", "N", "B"):
        if f"{car}_{tag}_color" in images:
            look(f"{car}_{tag}", f"{car}_{tag}")
    if f"{car}_sign" in images:
        look(f"{car}_Sign", f"{car}_sign", pbr=False, normal=f"{car}_signnormal" if f"{car}_signnormal" in images else None)
model = {"className": "Folder", "children": children}
json.dump(model, open(os.path.join(ROOT, "src", "server", "TrainLooks.model.json"), "w"), indent=1)
print("wrote Config/TrainShell.luau and TrainLooks.model.json:", [c["name"] for c in children])
