"""
Writes the runtime's view of the uploaded exterior from assets/train/asset_ids.json:

  python tools/trainshell/gen_config.py

  src/shared/Config/TrainShell.luau     mesh ids, centres and sizes in train space, livery roles
  src/server/TrainLooks.model.json      SurfaceAppearance templates (Rojo -> ServerScriptService.Server.TrainLooks)

Car pieces are named <Car>_<Piece>; kit pieces (DoorLeafL/R, Bogie, Wheel) carry an `anchor`:
where the primitive they stand in for has its centre, in the kit's own frame.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ids = json.load(open(os.path.join(ROOT, "assets", "train", "asset_ids.json")))

CARS = {
    "GuardsVan": (-90, -66),
    "LastTrainOut": (-63, -44.5),
    "CrewSaloon": (-41.5, -23),
    "Workshop": (-20, -1.5),
    "Stores": (1.5, 20),
}
PIECES = {
    # piece: livery role, look, casts a shadow
    "Shell": ("Body", "{car}", True),
    "Trim": ("Trim", "{car}", False),
    "Roof": ("Roof", "{car}", True),
    "Lens": ("Lamp", None, False),
    "Sign": (None, "{car}_Sign", False),
}
KIT = {
    "DoorLeafL": ((0, 0, 0), "Accent"),
    "DoorLeafR": ((0, 0, 0), "Accent"),
    "Bogie": ((0, -3, 0), None),
    "Wheel": ((0, 0, 0), None),
}


def num(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def vec(v):
    return "{ " + ", ".join(num(x) for x in v) + " }"


lines = [
    "--!strict",
    "--[[",
    "\tThe train's Blender exterior, as uploaded (generated by tools/trainshell/gen_config.py from",
    "\tassets/train/asset_ids.json; do not edit by hand). Centres and sizes are train space (studs).",
    "\tBuilders/TrainShell puts these on the primitive train; set Enabled = false for the old look.",
    "]]",
    "",
    "export type Piece = {",
    "\tmesh: number,",
    "\tcenter: { number },",
    "\tsize: { number },",
    "\tlivery: string?,",
    "\tlook: string?,",
    "\tshadow: boolean,",
    "}",
    "",
    "export type KitPiece = {",
    "\tmesh: number,",
    "\tcenter: { number },",
    "\tsize: { number },",
    "\tanchor: { number },",
    "\tlivery: string?,",
    "}",
    "",
    "export type Car = { x0: number, x1: number, pieces: { [string]: Piece } }",
    "",
    "local TrainShell: {",
    "\tEnabled: boolean,",
    "\tKitLook: string,",
    "\tLampLight: { Range: number, Brightness: number },",
    "\tCars: { [string]: Car },",
    "\tKit: { [string]: KitPiece },",
    "} = {",
    "\tEnabled = true,",
    '\tKitLook = "Kit",',
    "\t-- a steady glow under each door lamp, so the doors read from the platform at night",
    "\tLampLight = { Range = 9, Brightness = 0.7 },",
    "\tCars = {",
]
meshes = ids["meshes"]
for car, (x0, x1) in CARS.items():
    found = [p for p in PIECES if f"{car}_{p}" in meshes]
    if not found:
        continue
    lines.append(f"\t\t{car} = {{")
    lines.append(f"\t\t\tx0 = {num(x0)},")
    lines.append(f"\t\t\tx1 = {num(x1)},")
    lines.append("\t\t\tpieces = {")
    for p in found:
        m = meshes[f"{car}_{p}"]
        livery, look, shadow = PIECES[p]
        fields = [f"mesh = {m['id']}", f"center = {vec(m['center'])}", f"size = {vec(m['size'])}"]
        if livery:
            fields.append(f'livery = "{livery}"')
        if look:
            fields.append(f'look = "{look.format(car=car)}"')
        fields.append(f"shadow = {'true' if shadow else 'false'}")
        lines.append(f"\t\t\t\t{p} = {{ " + ", ".join(fields) + " },")
    lines.append("\t\t\t},")
    lines.append("\t\t},")
lines.append("\t},")
lines.append("\tKit = {")
for k, (anchor, livery) in KIT.items():
    m = meshes[k]
    fields = [f"mesh = {m['id']}", f"center = {vec(m['center'])}", f"size = {vec(m['size'])}", f"anchor = {vec(anchor)}"]
    if livery:
        fields.append(f'livery = "{livery}"')
    lines.append(f"\t\t{k} = {{ " + ", ".join(fields) + " },")
lines.append("\t},")
lines.append("}")
lines.append("")
lines.append("return TrainShell")
open(os.path.join(ROOT, "src", "shared", "Config", "TrainShell.luau"), "w", newline="\n").write("\n".join(lines) + "\n")

# SurfaceAppearance templates
images = ids["images"]
children = []


def look(name, prefix, pbr=True):
    props = {"AlphaMode": "Overlay"}  # the part's (livery) colour shows under the colour map's alpha
    props["ColorMap"] = f"rbxassetid://{images[prefix + '_color' if pbr else prefix]}"
    if pbr:
        props["NormalMap"] = f"rbxassetid://{images[prefix + '_normal']}"
        props["RoughnessMap"] = f"rbxassetid://{images[prefix + '_rough']}"
        props["MetalnessMap"] = f"rbxassetid://{images[prefix + '_metal']}"
    children.append({"name": name, "className": "SurfaceAppearance", "properties": props})


look("Kit", "Kit")
for car in CARS:
    if f"{car}_color" in images:
        look(car, car)
    if f"{car}_sign" in images:
        look(f"{car}_Sign", f"{car}_sign", pbr=False)
model = {"className": "Folder", "children": children}
json.dump(model, open(os.path.join(ROOT, "src", "server", "TrainLooks.model.json"), "w"), indent=1)
print("wrote Config/TrainShell.luau and TrainLooks.model.json:", [c["name"] for c in children])
